### ISSUE TITLE
Flutter 3: WidgetsBinding warnings

### ISSUE THREAD

**Issue by joshuadeguzman** [micazi/rich_text_controller#29]
```
../../../../Tools/flutter-3/.pub-cache/hosted/pub.dartlang.org/rich_text_controller-1.4.0/l
ib/rich_text_controller.dart:89:28: Warning: Operand of null-aware operation '?.' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('../../../../Tools/flutter-3/packages/flutter/lib/src/widgets/binding.dart').
            WidgetsBinding.instance?.addPostFrameCallback((_) {
                           ^
```

**Comment by RahmiTufanoglu** [comment]
Use this fork:

```
  rich_text_controller:
    git:
      url: https://github.com/RahmiTufanoglu/rich_text_controller.git
      ref: fix_widgets_binding_warning
```
